//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.4
//
// <auto-generated>
//
// Generated from file `Hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.Test2.TestInterface2;

/** @hidden */
public class _TestCallBackPrxI extends com.zeroc.Ice._ObjectPrxI implements TestCallBackPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
