//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.4
//
// <auto-generated>
//
// Generated from file `Hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package TestInterface1;

/** @hidden */
public class _TestPrxI extends com.zeroc.Ice._ObjectPrxI implements TestPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
